pipeline {
    agent {
        docker {
            image 'maven:3.3-jdk-8'
        }
    }
    stages {
        stage('compile') {
            steps {
                sh 'mvn compile'
            }
        }
    }
}